version: '3.8'

services:
  web:
    image: ghcr.io/zeecka/aperisolve-web:latest
    container_name: aperisolve_web
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - backend
      - mongodb

  backend:
    image: ghcr.io/zeecka/aperisolve-backend:latest
    container_name: aperisolve_back
    ports:
      - "5001:5001"
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth --bind_ip_all
    env_file:
      - .env
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
