name: Docker Image CI

on:
  push:
    tags:
    - '*'

jobs:

  docker-releases-web:

    runs-on: ubuntu-latest
    steps:
    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: downcase username
      run: echo "lower_actor=${GITHUB_ACTOR,,}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
          context: ./web/
          push: true
          tags: |
                 ghcr.io/${{ env.lower_actor }}/aperisolve-web:latest
                 ghcr.io/${{ env.lower_actor }}/aperisolve-web:${{ env.RELEASE_VERSION }}
  
  docker-releases-backend:

    runs-on: ubuntu-latest
    steps:
    - name: Get release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: downcase username
      run: echo "lower_actor=${GITHUB_ACTOR,,}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
          context: ./backend/
          push: true
          tags: |
                 ghcr.io/${{ env.lower_actor }}/aperisolve-backend:latest
                 ghcr.io/${{ env.lower_actor }}/aperisolve-backend:${{ env.RELEASE_VERSION }}

